config/routes.rb
NewHire3000Xp::Application.routes.draw do
    resources :new_hires
    resources :contacts

    root to: 'static_pages#home'

    match '/new',  to: 'new_hires#new'
    match '/help',  to: 'static_pages#help'
    match '/about', to: 'static_pages#about'
    
    match '/laptop/:id', to: 'new_hires#update_laptop'
    match '/badge/:id', to: 'new_hires#update_badge'
    match '/vpn/:id', to: 'new_hires#update_vpn'
    match '/seat/:id', to: 'new_hires#update_seat'
    match '/docs/:id', to: 'new_hires#update_docs'
    match '/irc/:id', to: 'new_hires#update_irc'
    match '/vm/:id', to: 'new_hires#update_vm'    

end

app/models/new_hire.rb
# == Schema Information
#
# Table name: new_hires
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  email            :string(255)
#  start_date       :string(255)
#  office_location  :string(255)
#  type_of_computer :string(255)
#  department       :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  laptop           :integer          default(0)
#  badge            :integer          default(0)
#  vpn              :integer          default(0)
#  seat             :integer          default(0)
#  docs             :integer          default(0)
#  irc              :integer          default(0)
#  vm               :integer          default(0)
#

class NewHire < ActiveRecord::Base
  attr_accessible :department, :email, :name, :office_location, :start_date, :type_of_computer,
                  :laptop, :badge, :vpn, :seat, :docs, :irc, :vm, :manager

  before_save { |user| user.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[oracle]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :department, presence: true, length: { maximum: 50 }
  validates :office_location, presence: true, length: { maximum: 200 }
  validates :start_date, presence: true, length: { maximum: 30 }
  validates :type_of_computer, presence: true, length: { maximum: 30 }
  validates :manager, presence: true, length: { maximum: 30 }
  
  def self.search(search)
    if search
      where 'name LIKE ? ', "%#{search}%"
    else
      scoped
    end
  end               
end

app/controllers/new_hires_controller.rb
class NewHiresController < ApplicationController
  
  def show
      @new_hire = NewHire.find(params[:id])
      @contact_laptop = Contact.find_by_todo("Laptop")
      @contact_badge = Contact.find_by_todo("Badge")
      @contact_vpn = Contact.find_by_todo("Setup VPN")
      @contact_seat = Contact.find_by_todo("Find Seat")
      @contact_docs = NewHire.find(params[:id])
      @contact_irc = Contact.find_by_todo("Setup IRC")
      @contact_vm = Contact.find_by_todo("Setup VM")
  end
  
  def new
      @new_hire = NewHire.new
  end
  
  def create
    @new_hire = NewHire.new(params[:new_hire])
    if @new_hire.save
      flash[:success] = "Thanks for adding a new hire! A welcome email has been sent to new hire."
      redirect_to new_hires_path
      NewHireMailer.welcome_email(@new_hire).deliver
    else
      render 'new'
    end
  end
  
  def edit
    @new_hire = NewHire.find(params[:id])
  end
  
  def update
      @new_hire = NewHire.find(params[:id])
      if @new_hire.update_attributes(params[:new_hire])
        # Handle a successful update.
        flash[:success] = "Profile updated"
        redirect_to @new_hire
      else
        render 'edit'
      end
    end
    
    def index
      @new_hires = NewHire.search(params[:search]).paginate(:page => params[:page])
    end
    
    def destroy
        NewHire.find(params[:id]).destroy
        flash[:success] = "New hire deleted."
        redirect_to new_hires_url
      end
      
    ######## todo list ########
    def update_laptop
      @new_hire = NewHire.find(params[:id])
      if params[:laptop]
        @new_hire.update_attributes(:laptop => params[:laptop])
      end
      if @new_hire.laptop == 3 || @new_hire.laptop == 4
        @contact_laptop = Contact.find_by_todo("Laptop")
        NewHireMailer.laptop_email(@contact_laptop, @new_hire).deliver
        flash[:success] = "Laptop email sent!"
      #elsif @new_hire.laptop == 2 || @new_hire.laptop == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.laptop == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_badge
      @new_hire = NewHire.find(params[:id])
      if params[:badge]
        @new_hire.update_attributes(:badge => params[:badge])
      end
      if @new_hire.badge == 3 || @new_hire.badge == 4
        @contact_badge = Contact.find_by_todo("Badge")
        NewHireMailer.badge_email(@contact_badge, @new_hire).deliver
        flash[:success] = "Badge email sent!"
      #elsif @new_hire.badge == 2 || @new_hire.badge == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.badge == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_vpn
      @new_hire = NewHire.find(params[:id])
      if params[:vpn]
        @new_hire.update_attributes(:vpn => params[:vpn])
      end
      if @new_hire.vpn == 3 || @new_hire.vpn == 4
        @contact_vpn = Contact.find_by_todo("Setup VPN")
        NewHireMailer.VPN_email(@contact_vpn, @new_hire).deliver
        flash[:success] = "VPN email sent!"
      #elsif @new_hire.vpn == 2 || @new_hire.vpn == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.vpn == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_seat
      @new_hire = NewHire.find(params[:id])
      if params[:seat]
        @new_hire.update_attributes(:seat => params[:seat])
      end
      if @new_hire.seat == 3 || @new_hire.seat == 4
        @contact_seat = Contact.find_by_todo("Find Seat")
        NewHireMailer.seat_email(@contact_seat, @new_hire).deliver
        flash[:success] = "Seat placement email sent!"
      #elsif @new_hire.seat == 2 || @new_hire.seat == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.seat == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_docs
      @new_hire = NewHire.find(params[:id])
      if params[:docs]
        @new_hire.update_attributes(:docs => params[:docs])
      end
      if @new_hire.docs == 3 || @new_hire.docs == 4
        NewHireMailer.docs_email(@new_hire).deliver
        flash[:success] = "Document email sent!"
      #elsif @new_hire.docs == 2 || @new_hire.docs == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.docs == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_irc
      @new_hire = NewHire.find(params[:id])
      if params[:irc]
        @new_hire.update_attributes(:irc => params[:irc])
      end
      if @new_hire.irc == 3 || @new_hire.irc == 4
        @contact_irc = Contact.find_by_todo("Setup IRC")
        NewHireMailer.IRC_email(@contact_irc, @new_hire).deliver
        flash[:success] = "IRC email sent!"
      #elsif @new_hire.irc == 2 || @new_hire.irc == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.irc == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
    
    def update_vm
      @new_hire = NewHire.find(params[:id])
      if params[:vm]
        @new_hire.update_attributes(:vm => params[:vm])
      end
      if @new_hire.vm == 3 || @new_hire.vm == 4
        @contact_vm = Contact.find_by_todo("Setup VM")
        NewHireMailer.VM_email(@contact_vm, @new_hire).deliver
        flash[:success] = "VM email sent!"
      #elsif @new_hire.vm == 2 || @new_hire.vm == 5
        #NewHireMailer.email_2(@new_hire).deliver
        #flash[:success] = "Email 2 sent!"
      elsif @new_hire.laptop == 1
        flash[:success] = "Work done!"
      end
      redirect_to @new_hire
    end
end

app/helpers/new_hires_helper.rb
module NewHiresHelper
end

app/views/new_hires/_badge.html.erb
<tr>
	<td><font size="4">Request keycard badge</font>
	<td><%= @contact_badge.name  %></td>
	
	<td>
		<% if @new_hire.badge == 0 %>
			<span class="label">Not started</span>
		<% elsif @new_hire.badge == 2 || @new_hire.badge == 3 || @new_hire.badge == 4 || @new_hire.badge == 5 %>
			<span class="label label-warning">In progress</span>
		<% else %>
			<span class="label label-success">Done</span>
		<% end %>
	</td>
	
	<td>
		<div class="btn-group">
			<% if @new_hire.badge == 0 %>、
			<% a = "chen"%>
		    	<%= link_to "Send Email", "/badge/#{@new_hire.id}?badge=3", class: "btn btn-small" %>
			<% elsif @new_hire.badge == 2 %>
				<%= link_to "Send Email", "/badge/#{@new_hire.id}?badge=4", class: "btn btn-small" %>
			<% elsif @new_hire.badge == 3 || @new_hire.badge == 4 || @new_hire.badge == 5 %>
				<%= link_to "Email Sent!", "#", class: "btn disabled btn-small" %>
		    <% end %>
		
		  <!-- Disabled this part
			<% if @new_hire.badge == 0 %>
		   	    <%= link_to "Send Email 2", "/badge/#{@new_hire.id}?badge=2", class: "btn btn-small" %>
			<% elsif @new_hire.badge == 3 %>
				<%= link_to "Send Email 2", "/badge/#{@new_hire.id}?badge=5", class: "btn btn-small" %>
			<% elsif @new_hire.badge == 2 || @new_hire.badge == 4 || @new_hire.badge == 5 %>
				<%= link_to "Email 2 sent", "#", class: "btn disabled btn-small" %>
		    <% end %>
			Disabled -->
					
			<%= link_to "reset", "/badge/#{@new_hire.id}?badge=0", class: "btn btn-small btn-dange" %>
			
			<% if @new_hire.badge != 1 %>
		    	<%= link_to "Done!", "/badge/#{@new_hire.id}?badge=1", class: "btn btn-success btn-small" %>
		    <% else %>
				<%= link_to "No more actions", "#", class: "btn disabled btn-small" %>
			<% end %>		
		</div>
	</td>
	
</tr>

app/views/new_hires/_docs.html.erb
<tr>
	<td><font size="4">Remind employee to bring I9 documents</font>
	<td><%= @contact_docs.name  %></td>
	
	<td>
		<% if @new_hire.docs == 0 %>
			<span class="label">Not started</span>
		<% elsif @new_hire.docs == 2 || @new_hire.docs == 3 || @new_hire.docs == 4 || @new_hire.docs == 5 %>
			<span class="label label-warning">In progress</span>
		<% else %>
			<span class="label label-success">Done</span>
		<% end %>
	</td>
	
	<td>
		<div class="btn-group">
			<% if @new_hire.docs == 0 %>
		    	<%= link_to "Send Email", "/docs/#{@new_hire.id}?docs=3", class: "btn btn-small" %>
			<% elsif @new_hire.docs == 2 %>
				<%= link_to "Send Email", "/docs/#{@new_hire.id}?docs=4", class: "btn btn-small" %>
			<% elsif @new_hire.docs == 3 || @new_hire.docs == 4 || @new_hire.docs == 5 %>
				<%= link_to "Email Sent!", "#", class: "btn disabled btn-small" %>
		    <% end %>
		
		 <!-- Disabled this part
			<% if @new_hire.docs == 0 %>
		   	    <%= link_to "Send Email 2", "/docs/#{@new_hire.id}?docs=2", class: "btn btn-small" %>
			<% elsif @new_hire.docs == 3 %>
				<%= link_to "Send Email 2", "/docs/#{@new_hire.id}?docs=5", class: "btn btn-small" %>
			<% elsif @new_hire.docs == 2 || @new_hire.docs == 4 || @new_hire.docs == 5 %>
				<%= link_to "Email 2 sent", "#", class: "btn disabled btn-small" %>
		    <% end %>
		 -->
			
			<%= link_to "reset", "/docs/#{@new_hire.id}?docs=0", class: "btn btn-small" %>
			
			<% if @new_hire.docs != 1 %>
		    	<%= link_to "Done!", "/docs/#{@new_hire.id}?docs=1", class: "btn btn-success btn-small" %>
		    <% else %>
				<%= link_to "No more actions", "#", class: "btn disabled btn-small" %>
			<% end %>
			
		</div>
	</td>
	
</tr>

app/views/new_hires/_irc.html.erb
<tr>
	<td><font size="4">Request IRC setup</font>
	<td><%= @contact_irc.name  %></td>
	
	<td>
		<% if @new_hire.irc == 0 %>
			<span class="label">Not started</span>
		<% elsif @new_hire.irc == 2 || @new_hire.irc == 3 || @new_hire.irc == 4 || @new_hire.irc == 5 %>
			<span class="label label-warning">In progress</span>
		<% else %>
			<span class="label label-success">Done</span>
		<% end %>
	</td>
	
	<td>
		<div class="btn-group">
			<% if @new_hire.irc == 0 %>
		    	<%= link_to "Send Email", "/irc/#{@new_hire.id}?irc=3", class: "btn btn-small" %>
			<% elsif @new_hire.irc == 2 %>
				<%= link_to "Send Email", "/irc/#{@new_hire.id}?irc=4", class: "btn btn-small" %>
			<% elsif @new_hire.irc == 3 || @new_hire.irc == 4 || @new_hire.irc == 5 %>
				<%= link_to "Email Sent!", "#", class: "btn disabled btn-small" %>
		    <% end %>
		  
		 <!-- Disabled this part
			<% if @new_hire.irc == 0 %>
		   	    <%= link_to "Send Email 2", "/irc/#{@new_hire.id}?irc=2", class: "btn btn-small" %>
			<% elsif @new_hire.irc == 3 %>
				<%= link_to "Send Email 2", "/irc/#{@new_hire.id}?irc=5", class: "btn btn-small" %>
			<% elsif @new_hire.irc == 2 || @new_hire.irc == 4 || @new_hire.irc == 5 %>
				<%= link_to "Email 2 sent", "#", class: "btn disabled btn-small" %>
		    <% end %>
		  -->
			
			<%= link_to "reset", "/irc/#{@new_hire.id}?irc=0", class: "btn btn-small" %>
			
			
			<% if @new_hire.irc != 1 %>
		    	<%= link_to "Done!", "/irc/#{@new_hire.id}?irc=1", class: "btn btn-success btn-small" %>
		    <% else %>
				<%= link_to "No more actions", "#", class: "btn disabled btn-small" %>
			<% end %>
			
		</div>
	</td>

</tr>

app/views/new_hires/_laptop.html.erb
<tr>
	<td><font size="4">Get a laptop</font>
	<td><%= @contact_laptop.name  %></td>
	
	<td>
		<% if @new_hire.laptop == 0 %>
			<span class="label">Not started</span>
		<% elsif @new_hire.laptop == 2 || @new_hire.laptop == 3 || @new_hire.laptop == 4 || @new_hire.laptop == 5 %>
			<span class="label label-warning">In progress</span>
		<% else %>
			<span class="label label-success">Done</span>
		<% end %>
	</td>
	
	<td>
		<div class="btn-group">
			<% if @new_hire.laptop == 0 %>
		    	<%= link_to "Send Email", "/laptop/#{@new_hire.id}?laptop=3", class: "btn btn-small" %>
			<% elsif @new_hire.laptop == 2 %>
				<%= link_to "Send Email", "/laptop/#{@new_hire.id}?laptop=4", class: "btn btn-small" %>
			<% elsif @new_hire.laptop == 3 || @new_hire.laptop == 4 || @new_hire.laptop == 5 %>
				<%= link_to "Email Sent!", "#", class: "btn disabled btn-small" %>
		    <% end %>
		
		   <!-- Disabled this part
			<% if @new_hire.laptop == 0 %>
		   	    <%= link_to "Send Email 2", "/laptop/#{@new_hire.id}?laptop=2", class: "btn btn-small" %>
			<% elsif @new_hire.laptop == 3 %>
				<%= link_to "Send Email 2", "/laptop/#{@new_hire.id}?laptop=5", class: "btn btn-small" %>
			<% elsif @new_hire.laptop == 2 || @new_hire.laptop == 4 || @new_hire.laptop == 5 %>
				<%= link_to "Email 2 sent", "#", class: "btn disabled btn-small" %>
		    <% end %>
			-->
			
			<%= link_to "reset", "/laptop/#{@new_hire.id}?laptop=0", class: "btn btn-small" %>			
		
			<% if @new_hire.laptop != 1 %>
		    	<%= link_to "Done!", "/laptop/#{@new_hire.id}?laptop=1", class: "btn btn-success btn-small" %>
		    <% else %>
				<%= link_to "No more actions", "#", class: "btn disabled btn-small" %>
			<% end %>
		</div>
	</td>
	
</tr>

app/views/new_hires/_new_hire.html.erb
<tr>
	<td>
		<font size=3><b><%= new_hire.name %></b></font>
		
		<%if (new_hire.laptop == 1 && new_hire.badge == 1 && new_hire.vpn == 1 && 
      new_hire.seat == 1 && new_hire.docs == 1 && new_hire.irc == 1 && new_hire.vm == 1) %>
			<span class="label label-success">Done</span>
    <% elsif (new_hire.laptop == 0 && new_hire.badge == 0 && new_hire.vpn == 0 && 
        new_hire.seat == 0 && new_hire.docs == 0 && new_hire.irc == 0 && new_hire.vm == 0) %>
			<span class="label">Not started</span>
    <% else %>
			<span class="label label-warning">In progress</span>
		<% end %>	
		
	</td>
	<td><%= new_hire.email %></td>
	<td><%= new_hire.department %></td>					
	<td>
	
	<%= link_to "to-do list", new_hire, class: "btn btn-small btn-primary" %>
	
	<div style="float:right;" class="btn-group">
	<%= link_to "edit", edit_new_hire_path(new_hire), class: "btn btn-small" %>	
		<%= link_to "delete", new_hire, method: :delete,
		                                  data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
	</div>
		
	</td>		
</tr>

app/views/new_hires/_progress_bar.html.erb
<% @total = 0 %>

<% if @new_hire.laptop == 0 %>
	<% laptopp = 0 %>
<% elsif @new_hire.laptop == 2 || @new_hire.laptop == 3 %>
	<% laptopp = 1 %>
<% else %>
	<% laptopp = 2 %>
<% end %>
	
<% if @new_hire.badge == 0 %>
	<% badgep = 0 %>
<% elsif @new_hire.badge == 2 || @new_hire.badge == 3 %>
	<% badgep = 1 %>
<% else %>
	<% badgep = 2 %>
<% end %>

<% if @new_hire.vpn == 0 %>
	<% vpnp = 0 %>
<% elsif @new_hire.vpn == 2 || @new_hire.vpn == 3 %>
	<% vpnp = 1 %>
<% else %>
	<% vpnp = 2 %>
<% end %>

<% if @new_hire.seat == 0 %>
	<% seatp = 0 %>
<% elsif @new_hire.seat == 2 || @new_hire.seat == 3 %>
	<% seatp = 1 %>
<% else %>
	<% seatp = 2 %>
<% end %>

<% if @new_hire.docs == 0 %>
	<% docsp = 0 %>
<% elsif @new_hire.docs == 2 || @new_hire.docs == 3 %>
	<% docsp = 1 %>
<% else %>
	<% docsp = 2 %>
<% end %>

<% if @new_hire.irc == 0 %>
	<% ircp = 0 %>
<% elsif @new_hire.irc == 2 || @new_hire.irc == 3 %>
	<% ircp = 1 %>
<% else %>
	<% ircp = 2 %>
<% end %>

<% if @new_hire.vm == 0 %>
	<% vmp = 0 %>
<% elsif @new_hire.vm == 2 || @new_hire.vm == 3 %>
	<% vmp = 1 %>
<% else %>
	<% vmp = 2 %>
<% end %>

<% @total = ((laptopp + badgep + vpnp + seatp + docsp + ircp + vmp)*7.14).ceil %>


<% if @total == 100 %>
	<h3><font color="green">You have finished the new hire todo list!</font></h3>
<% else %>
	<h3><%= "to-do list progress: #{@total}%" %></h3>
<% end %>

app/views/new_hires/_seat.html.erb
<tr>
	<td><font size="4">Find a seat</font>
	<td><%= @contact_seat.name  %></td>
	
	<td>
		<% if @new_hire.seat == 0 %>
			<span class="label">Not started</span>
		<% elsif @new_hire.seat == 2 || @new_hire.seat == 3 || @new_hire.seat == 4 || @new_hire.seat == 5 %>
			<span class="label label-warning">In progress</span>
		<% else %>
			<span class="label label-success">Done</span>
		<% end %>
	</td>
	
	<td>
		<div class="btn-group">
			<% if @new_hire.seat == 0 %>
		    	<%= link_to "Send Email", "/seat/#{@new_hire.id}?seat=3", class: "btn btn-small" %>
			<% elsif @new_hire.seat == 2 %>
				<%= link_to "Send Email", "/seat/#{@new_hire.id}?seat=4", class: "btn btn-small" %>
			<% elsif @new_hire.seat == 3 || @new_hire.seat == 4 || @new_hire.seat == 5 %>
				<%= link_to "Email Sent!", "#", class: "btn disabled btn-small" %>
		    <% end %>
		
		 <!-- Disabled this part
			<% if @new_hire.seat == 0 %>
		   	    <%= link_to "Send Email 2", "/seat/#{@new_hire.id}?seat=2", class: "btn btn-small" %>
			<% elsif @new_hire.seat == 3 %>
				<%= link_to "Send Email 2", "/seat/#{@new_hire.id}?seat=5", class: "btn btn-small" %>
			<% elsif @new_hire.seat == 2 || @new_hire.seat == 4 || @new_hire.seat == 5 %>
				<%= link_to "Email 2 sent", "#", class: "btn disabled btn-small" %>
		    <% end %>
				-->

			<%= link_to "reset", "/seat/#{@new_hire.id}?seat=0", class: "btn btn-small" %>
			
			
			<% if @new_hire.seat != 1 %>
		    	<%= link_to "Done!", "/seat/#{@new_hire.id}?seat=1", class: "btn btn-success btn-small" %>
		    <% else %>
				<%= link_to "No more actions", "#", class: "btn disabled btn-small" %>
			<% end %>
		
			
		</div>
	</td>

</tr>

app/views/new_hires/_to_do_list.html.erb
<aside class="span12">

	<div style="float:left;">
	<%= render 'progress_bar' %>
	</div>

<table class="table table-striped table-bordered">
	<thead>
	    <tr class="success">
	      <th class="span5">to-do</th>
				<th class="span3">person in charge</th>
				<th>status</th>
	      <th class="span3">available actions</th>			
	    </tr>
	</thead>

<%= render 'laptop' %>
<%= render 'badge' %>
<%= render 'vpn' %>
<%= render 'seat' %>
<%= render 'docs' %>
<%= render 'irc' %>
<%= render 'vm' %>

	<tr>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	</tr>
	
</table>
</aside>

app/views/new_hires/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update new hire information</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@new_hire) do |f| %>
      <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :oracle_email %>
        <%= f.text_field :email %>

        <%= f.label :start_date %>
        <%= datepicker_input "new_hire","start_date", :placeholder => 'MM/DD/YYYY'%>
				
				<%= f.label :manager %>
	      <%= f.text_field :manager %>

  	  <%= f.label :office_location %>
        <%= f.select :office_location, ["101 Marietta St. Suite 1700 Atlanta, GA 30303", "300 Oracle Pkwy. Redwood Shores, CA 94065", "13915 Burnet Rd., Suite 406, Austin, TX 78728", "475 Sansome St, 15th Floor, San Francisco, CA, 94111"]%>

  	  <%= f.label :type_of_computer %>
        <%= f.select :type_of_computer, ["Retina Macbook Pro", "Non-Retina Macbook Pro"]%>

  	  <%= f.label :department %>
        <%= f.select :department, ["Executive", "Outbound Product Management", "User Experience", "Program & Partner Management", "Inbound Product Management", "Engineering", "Engineering Infrastructure", "Quality Assurance", "Student / Interns"] %>
	  <br>
	  <br>
      <%= f.submit "Save", class: "btn btn-large btn-success" %>
      <%= link_to "Cancel", new_hire_url, class: "btn btn-large btn" %>	
    <% end %>


  </div>
</div>

app/views/new_hires/show.html.erb
<% if Contact.find_by_todo("Laptop") != nil && Contact.find_by_todo("Badge") != nil && Contact.find_by_todo("Setup VPN") != nil && Contact.find_by_todo("Find Seat") != nil && Contact.find_by_todo("Setup IRC") != nil && Contact.find_by_todo("Setup VM") != nil %>

<% provide(:title, @new_hire.name) %>
<div class="row">
  <aside class="span12">
    <section>
		<font size="5"><b><%= @new_hire.name %></b></font>	
	<div style="float:right;" class="btn-group">
 	<%= link_to "edit", edit_new_hire_path(@new_hire), class: "btn btn-small" %>	
	<%= link_to "delete", @new_hire, method: :delete,
	                      data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
	</div>
	  <p>
			<br>
			<i class="icon-envelope"></i><b>	Email:</b> 	     	
			<%= @new_hire.email %>
			<br>
			<i class="icon-calendar"></i><b>	Start date:</b>      
			<%= @new_hire.start_date %>
			<br>
			<i class="icon-user"></i><b>	Manager:</b>      
			<%= @new_hire.manager %>
			<br>
			<i class="icon-map-marker"></i><b>	Location:</b> 
			<%= @new_hire.office_location %>
			<br>
			<i class="icon-wrench"></i><b>	Computer:</b> 
			<%= @new_hire.type_of_computer %>
			<br>
			<i class="icon-home"></i><b>	Department:</b>      
			<%= @new_hire.department %>
	  </p>
    </section>
  </aside>

<%= render 'to_do_list' %>

</div>

<% else %>
	<% flash[:error] = "Please first complete the necessary contacts information within \"Settings\"  (completed #{Contact.count} out 6)" %> 
<% end %>