config/routes.rb
NewHire3000Xp::Application.routes.draw do
    resources :new_hires
    resources :contacts

    root to: 'static_pages#home'

    match '/new',  to: 'new_hires#new'
    match '/help',  to: 'static_pages#help'
    match '/about', to: 'static_pages#about'
    
    match '/laptop/:id', to: 'new_hires#update_laptop'
    match '/badge/:id', to: 'new_hires#update_badge'
    match '/vpn/:id', to: 'new_hires#update_vpn'
    match '/seat/:id', to: 'new_hires#update_seat'
    match '/docs/:id', to: 'new_hires#update_docs'
    match '/irc/:id', to: 'new_hires#update_irc'
    match '/vm/:id', to: 'new_hires#update_vm'    

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :todo
  validates :name, presence: true, length: { maximum: 50 }
  validates :todo, presence: true, length: { maximum: 50 },
  				   uniqueness: true
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[oracle]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new

  end


  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      flash[:success] = "Thanks for adding a new contact! A notification has been sent to the contact."
      redirect_to contacts_path
      NewHireMailer.contact_email(@contact).deliver
    else
      render 'new'
    end
  end

  def update
    @contact = Contact.find(params[:id])
    old_address = @contact.email
    if @contact.update_attributes(params[:contact])
      flash[:success] = "Contact updated"
        if @contact.email != old_address
          NewHireMailer.contact_email(@contact).deliver
          flash[:success] = "Contact updated, a notification has been sent to the new contact."
        end
      redirect_to contacts_path
    else
      render 'edit'
    end
      
  end

  def edit
    @contact = Contact.find(params[:id])
  end
  
  def index
    @contacts = Contact.all
  end

  def destroy
    Contact.find(params[:id]).destroy
    flash[:success] = "Contact deleted."
    redirect_to contacts_path
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<tr>
	<td><font size="4"><%= contact.todo %></font></td>
	<td><%= contact.name %></td>
	<td><%= contact.email %>
	<div style="float:right;" class="btn-group">
	<%= link_to "edit", edit_contact_path(contact), class: "btn btn-small" %>
	<%= link_to "delete", contact, method: :delete,
	                                  data: { confirm: "You sure?" }, class: "btn btn-small btn-danger" %>
	</div>
	</td>				
</tr>

app/views/contacts/edit.html.erb
<% provide(:title, 'Edit Contact') %>

<h1>Edit Contact Information</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@contact) do |f| %>

	  <%= render 'shared/error_message_contact' %>

		<%= f.label :todo %> 
	  <%= f.text_field :todo, :disabled => true%>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :oracle_email %>
	  <%= f.text_field :email %>
	
		<p> * a notification email will be sent to new email address </p>
			<%= f.submit "Save", class: "btn btn-large btn-success" %>
			<%= link_to "Cancel", contacts_url, class: "btn btn-large btn" %>	
      <% end %>

  </div>
</div>

app/views/contacts/index.html.erb
<% provide(:title, 'All Contacts') %>

<h1>Settings</h1>
<h2>add contact information for each of the 6 items</h2>

<% if Contact.find_by_todo("Laptop") != nil && Contact.find_by_todo("Badge") != nil && Contact.find_by_todo("Setup VPN") != nil && Contact.find_by_todo("Find Seat") != nil && Contact.find_by_todo("Setup IRC") != nil && Contact.find_by_todo("Setup VM") != nil %>
<% else %>
	<% flash[:error] = "Please first complete the necessary contacts information within \"Settings\"  (completed #{Contact.count} out 6)" %> 
<% end %>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th> todo </th>
			<th> person in charge </th>
			<th> oracle email </th>
		</tr>
	<thead>
	<tbody>
    <%= render @contacts %>
	</tbody>
</table>

<% if Contact.count < 6 %>
	<%= link_to "Add contact", new_contact_path, class: "btn btn-primary" %>
<% else %>
	<%= link_to "You are ready to add new hires!", "#", class: "btn disabled" %>
<% end %>

app/views/contacts/new.html.erb
<% provide(:title, 'Add Contact!') %>

<% if Contact.find_by_todo("Laptop") != nil && Contact.find_by_todo("Badge") != nil && Contact.find_by_todo("Setup VPN") != nil && Contact.find_by_todo("Find Seat") != nil && Contact.find_by_todo("Setup IRC") != nil && Contact.find_by_todo("Setup VM") != nil %>
<% else %>
	<% flash[:error] = "Please first complete the necessary contacts information within \"Settings\"  (completed #{Contact.count} out 6)" %> 
<% end %>

<h1>Add A Contact</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@contact) do |f| %>

	  <%= render 'shared/error_message_contact' %>

			<%= f.label :todo, "Contact's responsbility" %>
			
			
			<% @list = ["Laptop", "Badge", "Find Seat", "Setup VPN", "Setup IRC", "Setup VM"] %>
	    <% Contact.all.each do |i| %>
	    <%  if i.todo == "Laptop" %>
	        <% @list.delete("Laptop") %>
	      <% elsif i.todo == "Badge" %>
	        <% @list.delete("Badge") %>
	      <% elsif i.todo == "Find Seat" %>
	        <% @list.delete("Find Seat") %>
	      <% elsif i.todo == "Setup VPN" %>
	        <% @list.delete("Setup VPN") %>
	      <% elsif i.todo == "Setup IRC" %>
	        <% @list.delete("Setup IRC") %>
	      <% elsif i.todo == "Setup VM" %>
	        <% @list.delete("Setup VM") %>
	      <% end %>
	    <% end %>
			
			
      <%= f.select :todo, @list %>
    	<%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :oracle_email %>
	  	<%= f.text_field :email %>

			<p> * a notification email will be sent to new contact </p>
      <%= f.submit "Add Contact", class: "btn btn-large btn-success" %>
    	<% end %>

  </div>
</div>