config/routes.rb
NewHire3000Xp::Application.routes.draw do
    resources :new_hires
    resources :contacts

    root to: 'static_pages#home'

    match '/new',  to: 'new_hires#new'
    match '/help',  to: 'static_pages#help'
    match '/about', to: 'static_pages#about'
    
    match '/laptop/:id', to: 'new_hires#update_laptop'
    match '/badge/:id', to: 'new_hires#update_badge'
    match '/vpn/:id', to: 'new_hires#update_vpn'
    match '/seat/:id', to: 'new_hires#update_seat'
    match '/docs/:id', to: 'new_hires#update_docs'
    match '/irc/:id', to: 'new_hires#update_irc'
    match '/vm/:id', to: 'new_hires#update_vm'    

end

app/views/layouts/_footer.html.erb
<footer class="footer">	
	
  <small>
    <%= link_to "New Hire 3000 XP", root_path %>
    by <a href="https://www.facebook.com/colourfulpanda?ref=tn_tnmn">Jiayuan Chen</a> and <a href="https://www.facebook.com/chris.bissell.52">Christopher Bissell</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
	  <li><%= link_to "Help",    help_path %></li>
    </ul>
  </nav>
	
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "New Hire 3000 XP", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
	      <li><%= link_to "≡ All Hires", new_hires_path %></li>
         <li><%= link_to "+ Add New",    new_path %></li>
         <li><%= link_to "⚙ Settings", contacts_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	      <% flash.each do |key, value| %>		<!--what does this flash do??-->
	        <div class="alert alert-<%= key %>"><%= value %></div>
	      <% end %>
	
	      <%= yield %>
	
	      <%= render 'layouts/footer' %>
	      <%= debug(params) if Rails.env.development? %>
	 </div>
  </body>
</html>